---
abstract: 'Command-line tool to query GitHub pull requests'
author:
  - 'Robin Smidsrød <robin@smidsrod.no>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-GitHubPullRequest
requires:
  Data::Dumper: 0
  FindBin: 0
  JSON: 0
  feature: 0
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/robinsmidsrod/App-GitHubPullRequest.git
version: 0.0.2
